automation: !include automations.yaml
mqtt: !include mqtt.yaml

input_number:
  esp_volume:
    icon: mdi:volume-medium
    name: Volume
    initial: 30
    min: 1
    max: 100
    step: 1

input_text:
  mqtt_value_input:
    name: MQTT Value Input
    initial: ""
    max: 255

input_boolean:
  led_mode:
    name: LED Mode
    initial: off
